// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(a
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAicG9CwrWAIUVkTsv4PiL-xDZqHrEv45A',
    appId: '1:273229911683:web:8ac2fa7376e644ab3dadb6',
    messagingSenderId: '273229911683',
    projectId: 'pktest-7db94',
    authDomain: 'pktest-7db94.firebaseapp.com',
    storageBucket: 'pktest-7db94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM_TC5CC8hhL3xHmklpx8syXjFCnTyl_o',
    appId: '1:273229911683:android:f4d672193dbf41893dadb6',
    messagingSenderId: '273229911683',
    projectId: 'pktest-7db94',
    storageBucket: 'pktest-7db94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUh8RuvJayzJUTo5WkLOcNnbT9ltHnKHo',
    appId: '1:273229911683:ios:27681e800821979a3dadb6',
    messagingSenderId: '273229911683',
    projectId: 'pktest-7db94',
    storageBucket: 'pktest-7db94.appspot.com',
    iosClientId: '273229911683-j3ocbo2vj3cmer3soh19o2sj3502pcfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pkTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUh8RuvJayzJUTo5WkLOcNnbT9ltHnKHo',
    appId: '1:273229911683:ios:ef2520a563e87e193dadb6',
    messagingSenderId: '273229911683',
    projectId: 'pktest-7db94',
    storageBucket: 'pktest-7db94.appspot.com',
    iosClientId: '273229911683-j9tmqg4rm69s7c2danheeojrlspo52r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pkTest.RunnerTests',
  );
}
